---
name: "Docs-link-checker"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 23 */2 * *

env:
  DISABLE_TELEMETRY: 1

jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: ".mlc_config.json"
          folder-path: "manuscript/"
